version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: workbuddy_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  redis:
    image: redis:latest
    container_name: workbuddy_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
