version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: workbuddy_mongo
    ports:
      - "9401:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
  redis:
    image: redis:latest
    container_name: workbuddy_redis
    ports:
      - "9402:6379"
    volumes:
      - ./redis-data:/data
