spring:
  application:
    name: WorkBuddy
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: workBuddy
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  cache:
    type: redis
    time-to-live:
      general: 1800
      otp: 180
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL:email@email.com}
    password: ${SENDER_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_URI:localhost:9092}
    admin:
      auto-create-topics: true
    consumer:
      group-id: workbuddy-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 9401
  servlet:
    contextPath: /api/workbuddy
logging:
  file:
    name: workbuddy.log
security:
  jwt:
    secret-key: d27af2af4564fd3835df7b07655190e8850464de8b3c46ec0e49aafa4c562f7d
    expiration-time: 3600000