spring:
  application:
    name: WorkBuddy
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: workBuddy
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  cache:
    type: redis
    redis:
      time-to-live: 3600s
server:
  port: 9401
  servlet:
    contextPath: /api/workbuddy
logging:
  file:
    name: workbuddy.log