spring:
  application:
    name: WorkBuddy
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: workBuddy
      username: ${MONGO_ROOT_USERNAME:admin}
      password: ${MONGO_ROOT_PASSWORD:password}
      authentication-database: admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 3600s
server:
  port: 9400
  servlet:
    contextPath: /workbuddy
logging:
  file:
    name: workbuddy.log