spring:
  application:
    name: WorkBuddy
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: workBuddy
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  cache:
    type: redis
    time-to-live:
      general: 3600
      otp: 120
server:
  port: 9401
  servlet:
    contextPath: /api/workbuddy
logging:
  file:
    name: workbuddy.log
security:
  jwt:
    secret-key: d27af2af4564fd3835df7b07655190e8850464de8b3c46ec0e49aafa4c562f7d
    expiration-time: 3600000